on:
  issue_comment:
    types: [created, deleted]

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

  build:
    if: github.event.issue.pull_request && (github.event.comment.body == '/vrt')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.issue.pull_request }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build Storybook
        run: yarn build-storybook

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v3.4.0
