on:
  pull_request:
    types: labeled

jobs:
  baseline:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'run-vrt'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

      - if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: yarn install --immutable

      - name: Build Storybook
        run: yarn build-storybook

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v3.4.0
        env:
          FAIL_ON_DIFFERENCE: true
          LOST_PIXEL_MODE: update

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: lost-pixel-baseline
          path: .lostpixel/baseline
          retention-days: 1

  current:
    runs-on: ubuntu-latest
    needs: baseline
    if: github.event.label.name == 'run-vrt'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

      - if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: yarn install --immutable

      - name: Build Storybook
        run: yarn build-storybook

      - name: Download baseline
        uses: actions/download-artifact@v3
        with:
          name: lost-pixel-baseline
          path: .lostpixel/baseline

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v3.4.0

      # VRTの差分があるかどうかを変数に保存する
      - name: Output Parameter Which Is True When Changes Are Detected
        id: check-diff
        run: |
          if [ -z "$(find ".lostpixel/difference" -mindepth 1 -maxdepth 1)" ]; then
            echo "IS_VRT_CHANGED=false" >> "$GITHUB_OUTPUT"
          else
            echo "IS_VRT_CHANGED=true" >> "$GITHUB_OUTPUT"
          fi

      - name: upload
        # 差分があるときのみアップロードする
        if: steps.check-diff.outputs.IS_VRT_CHANGED == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: lost-pixel-result
          path: .lostpixel
          retention-days: 7

      # 差分があるときは失敗させる。
      - name: exit if diff is found
        if: steps.check-diff.outputs.IS_VRT_CHANGED == 'true'
        run: exit 1
